### ISSUE TITLE
Facing CORS error while uploading file from another domain

### ISSUE THREAD

**Issue by faridv** [smatsson/tusdotnet#2]
Hi,
While trying to implement your code, everything works with Tus JS clinet, as long I don't need CORS. By using another url for upload services and another domain for client-side app, I face 404 error on PATCH request.
How can I fix this error?

**Comment by smatsson** [comment]
Hi! 

What you need to do is enable CORS on the server. I think the easiest way to do this is to install the Nuget package Microsoft.Owin.Cors and then set it up as below:

`	var corsPolicy = new CorsPolicy
			{
				AllowAnyHeader = true,
				AllowAnyMethod = true,
				AllowAnyOrigin = true,
				ExposedHeaders = { "Location" },
				SupportsCredentials = true
			};

			app.UseCors(new CorsOptions
			{
				PolicyProvider = new CorsPolicyProvider
				{
					PolicyResolver = context => Task.FromResult(corsPolicy)
				}
			});
// app.UseTus(...) goes here
`

Please note that you need to add Location as "Exposed headers" as it is not exposed by default.

**Comment by faridv** [comment]
Thanks for your reply!
I used your js file and instead of `404`, I get `405 Method Not Allowed` on `PATCH` requests. `OPTIONS` and `POST` request are working by the way. `404` happens when `X-HTTP-Method-Override` is set to true and tus uses `POST` instead of `PATCH`.

**Comment by mjpournassari** [comment]
I used your js file and instead of `404`, I get `405 Method Not Allowed` on `PATCH` requests. `OPTIONS` and `POST` request are working by the way. `404` happens when `X-HTTP-Method-Override` is set to true and tus uses `POST` instead of `PATCH`.

**Comment by faridv** [comment]
@smatsson Thanks for your reply. I'm still having the same problem. My tus server is running on `127.0.0.1:81` and my front-end application is running on `127.0.0.1:82`, all I get is CORS errors in console.

**Comment by smatsson** [comment]
@mjpournassari  X-HTTP-Method-Override is not yet implemented as per the roadmap so that will not work. Are you running the site as a web application? In that case you need to update your web.config to run your code for all types of HTTP verbs:

```
<system.webServer>
		<validation validateIntegratedModeConfiguration="false"/>
		<handlers>
			<remove name="ExtensionlessUrlHandler-Integrated-4.0" />
			<remove name="OPTIONSVerbHandler" />
			<remove name="TRACEVerbHandler" />
			<add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
		</handlers>
		<modules runAllManagedModulesForAllRequests="true">
			<remove name="ApplicationInsightsWebTracking"/>
			<remove name="WebDAVModule" />
		</modules>
	</system.webServer>
```

**Comment by smatsson** [comment]
@faridv Please try the answer to @mjpournassari and see if that helps. Otherwise, please provide the code you have so that I can have a look. I tested the same thing earlier this morning with two sites running on localhost:8080 and localhost:9000. Both of these were console apps (the OwinTestSite in the repo).

**Comment by mjpournassari** [comment]
@smatsson  Hi
My project is Web Api. In the web.config file  handlers are exists.
You can test my client by below address:
[http://93.190.24.246:82/upload.html](url)

**Comment by smatsson** [comment]
@mjpournassari Can't connect to the site. Did you add runAllManagedModulesForAllRequests="true"? If so, please provide me with the code that is not working (i.e. your solution) and I'll have a look.

**Comment by mjpournassari** [comment]
@smatsson  Yes runAllManagedModulesForAllRequests="true.
I attached my Web Api project.

[SERVICE.zip](https://github.com/smatsson/tusdotnet/files/552993/SERVICE.zip)

**Comment by mjpournassari** [comment]
@smatsson Please try again to connect to [http://93.190.24.246:82/upload.html](http://93.190.24.246:82/upload.html)

**Comment by smatsson** [comment]
@mjpournassari Still can't connect but it doesn't really matter. Viewing your upload page does not give me any info that your solution won't give me. I'll have a look at it when I get the time.

**Comment by mjpournassari** [comment]
@smatsson  Thank you

**Comment by smatsson** [comment]
@mjpournassari I have looked at your code and this is not related to CORS. I have opened issue #3 were we can continue, so that @faridv can get help with his CORS issues in this issue. I have moved our comments to #3

**Comment by smatsson** [comment]
@faridv Did you manage to solve the issue?

**Comment by faridv** [comment]
@smatsson No, I couldn't. But it seems that me and @mjpournassari are facing the same issue.
server config is OK but `PATCH` requests are being sent to my `localhost/null`.

**Comment by smatsson** [comment]
@faridv I don't think the two issues are related at all. @mjpournassari's issue was that he was using an old version of tus-js-client that did not properly support relative URLs for cross domain (i.e. /files/<id> from localhost:82 was sent to localhost:81/files/id if the tus-js-client was hosted on localhost:81). This was fixed in an update to the client.

In your case, there seems to be an issue reading the Location header. Does your browser console contain any CORS related warnings?

**Comment by smatsson** [comment]
No answer for 21 days. I'll consider this one solved. F

or any other readers of this issue, the problem with the `localhost/null` address might be an issue with an old broken URL. tus-js-client will save URLs it receives for a specific file (otherwise it doesn't know if it should continue the upload or start a new one). If this URL is broken then future uploads for the same file will also be broken. Clear the sites local storage to remove all existing urls.
